=== Dzemite/stomatology/services/cd-proxy/config/config.schema.json
{
    "$schema": "http://json-schema.org/schema",
    "id": "http://link.to.github",
    "title": "TehLab Forms auth service schema",
    "type": "object",
    "properties": {
        "$schema": {
            "type": "string"
        },
        "jwtSecret": {
            "type": "string"
        },
        "port": {
            "type": "number"
        },
        "mongoDbUrl": {
            "type": "string"
        },
        "mongoCollectionName": {
            "type": "string"
        },
        "mongoArchiveCollectionName": {
            "type": "string"
        },
        "authServiceUrl": {
            "type": "string"
        }
    },
    "required": [
        "$schema",
        "port",
        "jwtSecret",
        "mongoDbUrl",
        "mongoCollectionName",
        "mongoArchiveCollectionName",
        "authServiceUrl"
    ],
    "additionalProperties": false
}

=== Dzemite/stomatology/services/pd-proxy/config/config.json
{
    "$schema": "./config.schema.json",
    "port": 8082,
    "jwtSecret": "testJwtSecret",    
    "mongoDbUrl": "mongodb://test-emkp-onko-base.teh-lab.ru:17027/PdProxy",
    "mongoCollectionName": "patients",
    "mongoArchiveCollectionName": "archivePD",
    "authServiceUrl": "https://test-audit-auth.teh-lab.ru"
}

=== Dzemite/stomatology/services/cd-proxy/config/config.json
{
    "$schema": "./config.schema.json",
    "port": 8081,
    "jwtSecret": "testJwtSecret",    
    "mongoDbUrl": "mongodb://test-emkp-onko-base.teh-lab.ru:17027/CdProxy",
    "mongoCollectionName": "CD",
    "mongoArchiveCollectionName": "archiveCD",
    "authServiceUrl": "https://test-audit-auth.teh-lab.ru"
}
